version: "3"

services:
  db:
    container_name: mysql-container
    build: ./mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    env_file: ./mysql/dev.env
